apiVersion: v1
kind: ServiceAccount
metadata:
  name: msm-admission-webhook-sa
  namespace: default

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: msm-admission-webhook-role
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
rules:
  - apiGroups: ["admissionregistration.k8s.io"]
    resources:
      - "mutatingwebhookconfigurations"
    verbs: ["*"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: msm-admission-webhook-binding
subjects:
  - kind: ServiceAccount
    name: msm-admission-webhook-sa
    namespace: default
roleRef:
  kind: ClusterRole
  name: msm-admission-webhook-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: Service
metadata:
  name: msm-admission-webhook-svc
  labels:
    app: msm-admission-webhook
spec:
  ports:
    - port: 443
      targetPort: 443
  selector:
    app: msm-admission-webhook

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: msm-admission-webhook
  labels:
    app: msm-admission-webhook
spec:
  selector:
    matchLabels:
      app: msm-admission-webhook
  template:
    metadata:
      labels:
        app: msm-admission-webhook
    spec:
      serviceAccount: msm-admission-webhook-sa
      containers:
        - name: msm-admission-webhook
          image: ciscolabs/msm-admission-webhook:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: REPO
              value: "ciscolabs"
            - name: TAG
              value: "latest"
            - name: MSM_SIDECAR
              value: "ubuntu-wait"
            - name: IMAGE_PULL_POLICY
              value: IfNotPresent
            - name: "LOG_LVL"
              value: "DEBUG"


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: msm-proxy-cfg
  namespace: default
data:
  conf.yml: |
    readTimeout: 5s
    writeTimeout: 5s
    server:
      protocols: [ tcp, udp ]
      rtspPort: 8554
      rtpPort: 8050
      rtcpPort: 8051
      readUser:
      readPass:

