# webhook-prep
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.webhookClusterRoleBinding }}
  labels:
    {{- include "msm.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.webhookServiceAccount }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.webhookClusterRole }}
  apiGroup: rbac.authorization.k8s.io
---
#cni-prep
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.cniClusterRole }}
  labels:
    {{- include "msm.labels" . | nindent 4 }}
    app: {{ .Values.cniClusterRole }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.cniClusterRole }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.cniClusterRole }}
---
#msm-controller
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: url-handler
  labels:
    {{- include "msm.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
