# cni-prep
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.cniClusterRole }}
  labels:
    {{- include "msm.labels" . | nindent 4 }}
    app: {{ .Values.cniClusterRole }}
---
# webhook-prep
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.webhookServiceAccount }}
  labels:
    {{- include "msm.labels" . | nindent 4 }}
