cni:
  hub: ""
  tag: ""
  image: msm-cni
  pullPolicy: ""

  # CNI bin and conf dir override settings
  # defaults:
  cniBinDir: /opt/cni/bin
  cniConfDir: /etc/cni/net.d
  cniConfFileName: ""

  excludeNamespaces:
    - msm-system

  # Chained = true; for deployments that support CNI plugin chain
  # Chained = false; for deployments that do not support CNI plugin chain
  chained: true

# For Helm compatibility.
ownerName: ""

global:
  # Default hub for MSM images.
  hub: docker.io/ciscolab

  # Default tag for MSM images.
  tag: latest

  # Image pull policy if default behavior isn't desired. (Default behavior => Always else IfNotPresent)
  imagePullPolicy: "Always"

  # For pulling any images in pods that reference this ServiceAccount.
  # Must be set for any cluster configured with a private docker registry.
  imagePullSecrets: []
  # - private-registry-key
