# rtsp-client
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rtsp-client
  labels:
    rtsp: client
    {{- include "msm-rtsp.labels" . | nindent 4 }}
  namespace: gbear
spec:
  replicas: 2
  selector:
    matchLabels:
      rtsp: client
  template:
    metadata:
      labels:
        rtsp: client
      annotations:
        sidecar.mediastreamingmesh.io/inject: "true"
    spec:
      containers:
        - name: rtsp-client
          image: ciscolabs/rtsp-client:latest
          imagePullPolicy: IfNotPresent
---
# rtsp-client 2
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rtsp-client2
  labels:
    rtsp: client
    {{- include "msm-rtsp.labels" . | nindent 4 }}
  namespace: gbear
spec:
  replicas: 2
  selector:
    matchLabels:
      rtsp: client
  template:
    metadata:
      labels:
        rtsp: client
      annotations:
        sidecar.mediastreamingmesh.io/inject: "true"
    spec:
      containers:
        - name: rtsp-client
          image: ciscolabs/rtsp-client:latest
          imagePullPolicy: IfNotPresent
---
# rtsp-server
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rtsp-server
  labels:
    app: rtsp
    {{- include "msm-rtsp.labels" . | nindent 4 }}
  namespace: gbear
spec:
  selector:
    matchLabels:
      app: rtsp
  template:
    metadata:
      labels:
        app: rtsp
      annotations:
        sidecar.mediastreamingmesh.io/inject: "true"
    spec:
      containers:
        - name: rtsp-server
          image: ciscolabs/rtsp-server:latest
          imagePullPolicy: IfNotPresent
        - name: rtsp-client
          image: ciscolabs/rtsp-client:latest
          imagePullPolicy: IfNotPresent
          command: ["ffmpeg"]
          args: ["-re", "-stream_loop", "-100", "-i", "/tmp/video.mjpeg", "-input_format", "mjpeg", "-an", "-pix_fmt", "yuvj420p", "-vcodec", "mjpeg", "-huffman", "default", "-f", "rtsp", "rtsp://0.0.0.0:554/mystream"]
          volumeMounts:
            - mountPath: /tmp
              name: movies
      volumes:
        - name: movies
          hostPath:
            path: /tmp
---
# rtsp-server 2
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rtsp-server2
  labels:
    app: rtsp2
    {{- include "msm-rtsp.labels" . | nindent 4 }}
  namespace: gbear
spec:
  selector:
    matchLabels:
      app: rtsp2
  template:
    metadata:
      labels:
        app: rtsp2
      annotations:
        sidecar.mediastreamingmesh.io/inject: "true"
    spec:
      containers:
        - name: rtsp-server
          image: ciscolabs/rtsp-server:latest
          imagePullPolicy: IfNotPresent
        - name: rtsp-client
          image: ciscolabs/rtsp-client:latest
          imagePullPolicy: IfNotPresent
          command: ["ffmpeg"]
          args: ["-re", "-stream_loop", "-100", "-i", "/tmp/video2.mjpeg", "-input_format", "mjpeg", "-an", "-pix_fmt", "yuvj420p", "-vcodec", "mjpeg", "-huffman", "default", "-f", "rtsp", "rtsp://0.0.0.0:554/mystream2"]
          volumeMounts:
            - mountPath: /tmp
              name: movies
      volumes:
        - name: movies
          hostPath:
            path: /tmp
