apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: msm-gateway
  labels:
    msm: gateway 
  namespace: default
spec:
  selector:
    matchLabels:
      msm: gateway 
  template:
    metadata:
      labels:
        msm: gateway 
    spec:
      hostNetwork: true
      containers:
        - name: msm-proxy
          image: ciscolabs/msm-proxy:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: rtp
              protocol: UDP
              containerPort: 8050
            - name: rtcp
              protocol: UDP
              containerPort: 8051
            - name: grpc
              protocol: TCP
              containerPort: 9000
        - name: msm-rtsp-stub
          image: ciscolabs/msm-rtsp-stub:latest
          imagePullPolicy: IfNotPresent 
          ports:
            - name: rtsp
              protocol: TCP
              containerPort: 8554
            - name: rtp
              protocol: UDP
              containerPort: 8000
            - name: rtcp
              protocol: UDP
              containerPort: 8001
          env:
            - name: MSM_LOG_LVL
              value: "TRACE"
            - name: MSM_DATA_PLANE
              value: "172.18.0.2"
            - name: MSM_CONTROL_PLANE
              value: "http://10.96.3.1:9000"
