apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: msm-cni
  labels:
    app: msm-cni
rules:
  - apiGroups: [""]
    resources:
      - pods
      - nodes
    verbs:
      - get
---

