apiVersion: v1
kind: ServiceAccount
metadata:
  name: msm-controller
  namespace: default
  labels:
    app: msm-controller
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: url-handler
  labels:
    app: msm-controller
rules:
  - apiGroups: [""]
    resources:
      - namespaces
      - services
      - nodes
      - endpoints
    verbs:
      - list
      - get
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: url-handler
roleRef:
  kind: ClusterRole
  name: url-handler
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: msm-controller
    namespace: default
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: node-watcher
  labels:
    app: msm-controller
rules:
  - apiGroups: [""]
    resources:
      - nodes
    verbs:
      - watch
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: node-watcher
  labels:
    app: msm-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: node-watcher
subjects:
  - kind: ServiceAccount
    name: msm-controller
    namespace: default