apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: msm-gateway
  labels:
    msm: gateway
  namespace: default
spec:
  selector:
    matchLabels:
      msm: gateway
  template:
    metadata:
      labels:
        msm: gateway
    spec:
      hostNetwork: true
      containers:
        - name: msm-proxy
          image: dockerhub.cisco.com/docker.io/ciscolabs/msm-proxy:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: rtp
              protocol: UDP
              containerPort: 8050
            - name: rtcp
              protocol: UDP
              containerPort: 8051
            - name: grpc
              protocol: TCP
              containerPort: 9000
          env:
            - name: LOG_LVL
              value: "DEBUG"
        - name: msm-rtsp-stub
          image: dockerhub.cisco.com/docker.io/ciscolabs/msm-rtsp-stub:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: rtsp
              protocol: TCP
              containerPort: 8554
          env:
            - name: MSM_LOG_LVL
              value: "DEBUG"
            - name: LOCAL_RTP_PORT
              value: "8000"
            - name: MSM_CONTROL_PLANE
              value: "http://10.96.3.1:9000"
            - name: MSM_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: MSM_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MSM_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace


