apiVersion: apps/v1
kind: Deployment
metadata:
  name: msm-controller
  labels:
    msm: controller
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      msm: controller
  template:
    metadata:
      labels:
        msm: controller
    spec:
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
      serviceAccountName: msm-controller
      containers:
        - name: msm-controller
          image: dockerhub.cisco.com/docker.io/ciscolabs/msm-controller:latest
          imagePullPolicy: Always
          ports:
            - name: grpc
              protocol: TCP
              containerPort: 9000
          env:
            - name: LOG_LVL
              value: "TRACE"
      nodeSelector:
        node-role.kubernetes.io/control-plane: ""