apiVersion: apps/v1
kind: Deployment
metadata:
  name: rtsp-server2
  labels:
    app: rtsp2
  namespace: default
spec:
  selector:
    matchLabels:
      app: rtsp2
  template:
    metadata:
      labels:
        app: rtsp2
      annotations:
        sidecar.mediastreamingmesh.io/inject: "true"
    spec:
      containers:
        - name: rtsp-server
          image: ciscolabs/rtsp-server:latest
          imagePullPolicy: IfNotPresent
        - name: rtsp-client
          image: ciscolabs/rtsp-client:latest
          imagePullPolicy: IfNotPresent
          command: ["ffmpeg"]
          args: ["-re", "-stream_loop", "-100", "-i", "/tmp/video2.mjpeg", "-input_format", "mjpeg", "-an", "-pix_fmt", "yuvj420p", "-vcodec", "mjpeg", "-huffman", "default", "-f", "rtsp", "rtsp://0.0.0.0:554/mystream2"]
          volumeMounts:
            - mountPath: /tmp
              name: movies
      volumes:
        - name: movies
          hostPath:
            path: /tmp
