# webhook
apiVersion: apps/v1
kind: Deployment
metadata:
  name: msm-admission-webhook
  labels:
    app: msm-admission-webhook
    {{- include "MSM.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: msm-admission-webhook
  template:
    metadata:
      labels:
        app: msm-admission-webhook
    spec:
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
      serviceAccount: msm-admission-webhook-sa
      containers:
        - name: msm-admission-webhook
          image: ciscolabs/msm-admission-webhook:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: REPO
              value: "ciscolabs"
            - name: TAG
              value: "20230215e"
            - name: MSM_SIDECAR
              value: "msm-rtsp-stub"
            - name: IMAGE_PULL_POLICY
              value: "IfNotPresent"
            - name: LOG_LVL
              value: "DEBUG"
            - name: MSM_LOG_LVL
              value: "DEBUG"
            - name: MSM_CONTROL_PLANE
              value: "http://10.43.3.1:9000"
      nodeSelector:
        node-role.kubernetes.io/control-plane: "true"

---
# msm-controller
apiVersion: apps/v1
kind: Deployment
metadata:
  name: msm-controller
  labels:
    msm: controller
    {{- include "MSM.labels" . | nindent 4 }}
  namespace: gbear
spec:
  replicas: 1
  selector:
    matchLabels:
      msm: controller
  template:
    metadata:
      labels:
        msm: controller
    spec:
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
      serviceAccountName: msm-controller
      containers:
        - name: msm-controller
          image: ciscolabs/msm-controller:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: grpc
              protocol: TCP
              containerPort: 9000
          env:
            - name: LOG_LVL
              value: "TRACE"
      nodeSelector:
        node-role.kubernetes.io/control-plane: "true"