# webhook
apiVersion: v1
kind: Service
metadata:
  name: msm-admission-webhook-svc
  labels:
    app: msm-admission-webhook
    {{- include "MSM.labels" . | nindent 4 }}
spec:
  clusterIP: 10.43.4.1
  ports:
    - port: 443
      targetPort: 443
  selector:
    app: msm-admission-webhook

---
#msm-controller-svc
apiVersion: v1
kind: Service
metadata:
  name: msm-controller
  labels:
    msm: controller
    {{- include "MSM.labels" . | nindent 4 }}
spec:
  clusterIP: 10.43.3.1
  ports:
    - name: grpc
      port: 9000
      targetPort: 9000
      protocol: TCP
  selector:
    msm: controller