# camera
apiVersion: apps/v1
kind: Deployment
metadata:
  name: camera
  labels:
    {{- include "Camera.labels" . | nindent 4 }}
    app: camera
  namespace: gbear
spec:
  selector:
    matchLabels:
      app: camera
  template:
    metadata:
      labels:
        app: camera
    spec:
      containers:
        - name: rtsp-server
          image: ciscolabs/rtsp-server:latest
          imagePullPolicy: IfNotPresent
        - name: rtsp-client
          image: ciscolabs/rtsp-client:latest
          imagePullPolicy: IfNotPresent
          command: ["ffmpeg"]
          args: ["-rtsp_transport", "tcp", "-i", "rtsp://msm:RUSTsuxr0x@82.36.109.33:8554/s1", "-an", "-c:v", "copy", "-f", "rtsp", "rtsp://127.0.0.1:554/giles-study"]
        - name: msm-rtsp-stub
          image: ciscolabs/msm-rtsp-stub:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: MSM_LOG_LVL
              value: "DEBUG"
            - name: MSM_CONTROL_PLANE
              value: "http://10.43.3.1:9000"