# cni-prep
apiVersion: v1
kind: ServiceAccount
metadata:
  name: msm-cni
  namespace: gbear
  labels:
    {{- include "MSM.labels" . | nindent 4 }}
    app: msm-cni
---
# webhook-prep
apiVersion: v1
kind: ServiceAccount
metadata:
  name: msm-admission-webhook-sa
  namespace: gbear
  labels:
    {{- include "MSM.labels" . | nindent 4 }}

---
# controller-prep
apiVersion: v1
kind: ServiceAccount
metadata:
  name: msm-controller
  namespace: gbear
  labels:
    app: msm-controller
    {{- include "MSM.labels" . | nindent 4 }}